const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
(async()=>{
  const browser=await chromium.launch({channel:'msedge',headless:true});
  try {
    const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
    const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));
    await page.route('**/*',route=>{if(route.request().url().startsWith('http://127.0.0.1:4186/'))return route.continue();external.push(route.request().url());return route.abort();});
    await page.goto('http://127.0.0.1:4186/');
    await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Recorded'),null,{timeout:30000});
    assert.equal(await page.locator('.plot').count(),8);
    assert.equal(await page.locator('#model-view').inputValue(),'engine');
    assert.equal(await page.locator('.engine-shape').count(),3);
    assert.ok((await page.locator('#model-objects').textContent()).includes('DampedSpring'));
    await page.locator('#equation-checks summary').click();
    assert.equal(await page.locator('#equation-values tr').count(),4);
    assert.ok((await page.locator('#equation-formulas').textContent()).includes('M_act_visible'));
    assert.ok((await page.locator('#equation-scope').textContent()).includes('pending'));
    assert.ok((await page.locator('#reference-validation').textContent()).includes('83.752875'));
    assert.equal(await page.locator('#equation-values').evaluate(n=>/NaN|undefined/.test(n.textContent)),false);
    await page.locator('#T0-kgf').fill('10');
    assert.ok(Math.abs(Number(await page.locator('#T0-newtons').inputValue())-98.0665)<1e-8);
    await page.locator('#T0-newtons').fill('49.03325');
    assert.ok(Math.abs(Number(await page.locator('#T0-kgf').inputValue())-5)<1e-8);
    assert.ok((await page.locator('#T0-conversion').textContent()).includes('kgf'));
    assert.ok((await page.locator('#joint-values').textContent()).includes('/'));
    await page.locator('#equation-checks summary').click();
    await page.locator('#model-view').selectOption('annotated');assert.equal(await page.locator('.engine-shape').count(),0);
    await page.locator('#model-view').selectOption('engine');assert.equal(await page.locator('.engine-shape').count(),3);
    assert.ok((await page.locator('#snapshot').textContent()).includes('200 mm wheel radius'));
    assert.ok((await page.locator('#snapshot').textContent()).includes('50 mm extension'));
    const scrub=async t=>page.locator('#time').evaluate((n,t)=>{n.value=t;n.dispatchEvent(new Event('input',{bubbles:true}));},t);
    await scrub(.25);const inputPath=await page.locator('.disturbance-profile').getAttribute('d');
    assert.equal(await page.locator('.disturbance-arrow').count(),0);
    await scrub(.35);assert.notEqual(await page.locator('.disturbance-profile').getAttribute('d'),inputPath);
    await scrub(.65);assert.equal(await page.locator('.disturbance-arrow').count(),1);
    assert.ok(Math.abs(Number(await page.locator('.disturbance-arrow').getAttribute('data-value'))-5)<1e-8);
    await scrub(.1);assert.equal(await page.locator('.disturbance-arrow').count(),0);
    const before=await page.locator('#pose-values').textContent();
    await page.locator('#play').click();await page.waitForTimeout(650);await page.locator('#play').click();
    assert.notEqual(await page.locator('#pose-values').textContent(),before);
    await page.locator('#time').evaluate(n=>{n.value=1.2;n.dispatchEvent(new Event('input',{bubbles:true}));});
    assert.equal(await page.locator('#time-value').textContent(),'1.200 s');
    await page.locator('#forces').check();await page.locator('#force-view').selectOption('fy');
    await page.locator('#probe').selectOption('j2');
    assert.ok((await page.locator('.plot h3').allTextContents()).includes('J2 pin acceleration'));
    const output=path.join(__dirname,'../artifacts');fs.mkdirSync(output,{recursive:true});
    await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true});
    const downloadPromise=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadPromise;
    await download.saveAs(path.join(output,'verified-trace.csv'));
    const csv=fs.readFileSync(path.join(output,'verified-trace.csv'),'utf8');assert.ok(csv.includes('j2_fx'));assert.ok(csv.includes('knee_accel'));assert.equal(csv.trim().split(/\r?\n/).length,6001);
    const configDownload=page.waitForEvent('download');await page.locator('#case').click();const savedConfig=await configDownload;await savedConfig.saveAs(path.join(output,'verified-run-config.json'));
    const caseData=JSON.parse(fs.readFileSync(path.join(output,'verified-run-config.json'),'utf8'));assert.equal(caseData.config.radius,.2);assert.equal(caseData.config.extension,.05);assert.equal(caseData.engine,'7.3.0');
    assert.ok(Math.abs(caseData.reference_inputs.T0_N-49.03325)<1e-8);
    assert.ok(Math.abs(caseData.reference_inputs.T0_kgf-5)<1e-8);
    assert.equal(caseData.reference_inputs.applied_to_solver,false);
    const set=async(key,value)=>{await page.locator(`[data-key="${key}"]`).evaluate(node=>node.closest('details').open=true);await page.locator(`[data-key="${key}"]`).fill(String(value));await page.locator(`[data-key="${key}"]`).dispatchEvent('change');};
    await set('duration',1.);await set('bias_force_x',27.590625);await page.locator('[data-key="wave"]').selectOption('impulse');
    await set('pulse_width',10);await page.locator('#run').click();await page.locator('#error').waitFor({state:'visible'});
    assert.ok((await page.locator('#error').textContent()).includes('Rise + fall'));
    await set('pulse_width',120);await set('impulse',.2);
    const responsePromise=page.waitForResponse(r=>r.url().endsWith('/api/simulate'));
    await page.locator('#run').click();const response=await responsePromise;const data=await response.json();assert.equal(response.status(),200);
    assert.ok(Math.abs(data.diagnostics.input_integral-.2)<1e-9);
    assert.equal(data.config.bias_force_x,27.590625);
    assert.ok(Object.values(data.equation_check_errors).every(x=>x<1e-7));
    await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Recorded'));
    await page.locator('[data-key="load_point"]').selectOption('contact');await page.locator('[data-key="wheel_drive_locked"]').check();
    const contactResponse=page.waitForResponse(r=>r.url().endsWith('/api/simulate'));await page.locator('#run').click();const contact=await (await contactResponse).json();
    assert.equal(contact.config.load_point,'contact');assert.equal(contact.config.wheel_drive_locked,true);
    assert.ok(contact.model.constraints.some(x=>x.name==='wheel_drive'));
    assert.ok(Math.abs(contact.rows.at(-1).wheel_external_moment-27.590625*.2)<1e-9);
    assert.ok(Object.values(contact.equation_check_errors).every(x=>x<1e-7));
    await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Recorded'));
    await page.locator('[data-key="fixture"]').selectOption('wheel');
    const wheelResponse=page.waitForResponse(r=>r.url().endsWith('/api/simulate'));await page.locator('#run').click();const wheel=await (await wheelResponse).json();
    assert.equal(wheel.config.fixture,'wheel');assert.equal(wheel.config.bias_force,0);
    await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Recorded'));
    assert.ok((await page.locator('#snapshot').textContent()).includes('Wheel fixed'));
    await page.locator('[data-key="target"]').selectOption('knee');
    const kneeResponse=page.waitForResponse(r=>r.url().endsWith('/api/simulate'));await page.locator('#run').click();const knee=await (await kneeResponse).json();assert.equal(knee.config.target,'knee');
    await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Recorded'));
    assert.equal(await page.locator('path').evaluateAll(ps=>ps.some(p=>/NaN|Infinity/.test(p.getAttribute('d')||''))),false);
    await scrub(.56);assert.equal(await page.locator('.disturbance-arrow').count(),1);
    assert.equal(await page.locator('.disturbance-arrow path').count(),2);
    await page.setViewportSize({width:390,height:1000});await page.waitForTimeout(150);
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});
    assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
    console.log('PASS: actual Pymunk backend, animation/scrub, force components, J2 probe, full CSV, invalid pulse rejection, impulse area, both fixtures, knee torque, responsive layout, offline assets, no browser errors.');
  } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
