const colors=['#a8730b','#286d8a','#657f3b','#8d5583'];
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const fmt=(v,d=2)=>Number.isFinite(v)?(v!==0&&(Math.abs(v)<.0001||Math.abs(v)>1e6)?v.toExponential(2):v.toLocaleString('en-US',{maximumFractionDigits:d})):'—';
let store=[],observers=[];
export function clearCharts(){observers.forEach(o=>o.disconnect());observers=[];store=[];}
export function chart({title,xLabel,yLabel,series,scatter=false,logX=false,subtitle='',zero=false}){const id=store.length;store.push({title,xLabel,yLabel,series,scatter,logX,zero});return `<section class="card plot-card" data-plot="${id}"><h3>${esc(title)}</h3>${subtitle?`<p>${esc(subtitle)}</p>`:''}<div class="legend">${series.map((s,i)=>`<span><i style="background:${s.color||colors[i%4]}"></i>${esc(s.label)}</span>`).join('')}</div><svg class="plot" tabindex="0" role="img" aria-label="${esc(title)}. ${esc(xLabel)}; ${esc(yLabel)}. Arrow keys inspect samples."></svg><output class="plot-tooltip" aria-live="polite">Move across the plot or use arrow keys to inspect values.</output></section>`;}
function reduce(points,n=900){if(points.length<=n)return points;const stride=points.length/(n/2),out=[points[0]];for(let i=0;i<points.length;i+=stride){const bucket=points.slice(Math.floor(i),Math.min(points.length,Math.floor(i+stride)));let lo=bucket[0],hi=lo;for(const p of bucket){if(p.y<lo.y)lo=p;if(p.y>hi.y)hi=p;}out.push(lo,hi);}out.push(points.at(-1));return out.sort((a,b)=>a.x-b.x);}
export function mountCharts(root){root.querySelectorAll('[data-plot]').forEach(el=>{const spec=store[Number(el.dataset.plot)],svg=el.querySelector('svg'),tip=el.querySelector('output');if(!spec)return;let width=500,height=290,extent,xy,index=0;
 const draw=()=>{width=Math.max(250,el.clientWidth-28);height=width<400?265:300;const l=62,r=16,t=15,b=53,pw=width-l-r,ph=height-t-b;const raw=spec.series.map((s,i)=>({...s,color:s.color||colors[i%4],points:s.points.filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)&&(!spec.logX||p.x>0))}));const xx=raw.flatMap(s=>s.points.map(p=>spec.logX?Math.log10(p.x):p.x)),yy=raw.flatMap(s=>s.points.map(p=>p.y));if(spec.zero){xx.push(0);yy.push(0);}let xmin=Infinity,xmax=-Infinity,ymin=Infinity,ymax=-Infinity;for(const v of xx){xmin=Math.min(xmin,v);xmax=Math.max(xmax,v);}for(const v of yy){ymin=Math.min(ymin,v);ymax=Math.max(ymax,v);}if(!xx.length){xmin=0;xmax=1;ymin=0;ymax=1;}if(xmin===xmax){xmin-=1;xmax+=1;}if(ymin===ymax){ymin-=1;ymax+=1;}const xp=(xmax-xmin)*.04,yp=(ymax-ymin)*.08;xmin-=xp;xmax+=xp;ymin-=yp;ymax+=yp;extent={xmin,xmax,ymin,ymax,l,t,pw,ph};xy=p=>[l+((spec.logX?Math.log10(p.x):p.x)-xmin)/(xmax-xmin)*pw,t+(ymax-p.y)/(ymax-ymin)*ph];let content='';for(let i=0;i<=4;i++){const y=ymin+(ymax-ymin)*i/4,sy=t+(4-i)*ph/4;content+=`<line x1="${l}" x2="${width-r}" y1="${sy}" y2="${sy}" stroke="#e6eadf"/><text x="${l-9}" y="${sy+4}" text-anchor="end">${fmt(y)}</text>`;}const ticks=width<400?2:4;for(let i=0;i<=ticks;i++){const v=xmin+(xmax-xmin)*i/ticks,sx=l+pw*i/ticks;content+=`<line x1="${sx}" x2="${sx}" y1="${t}" y2="${t+ph}" stroke="#e6eadf"/><text x="${sx}" y="${height-29}" text-anchor="${i===0?'start':i===ticks?'end':'middle'}">${fmt(spec.logX?10**v:v)}</text>`;}
 if(spec.zero){const zx=l+(0-xmin)/(xmax-xmin)*pw;content+=`<line x1="${zx}" x2="${zx}" y1="${t}" y2="${t+ph}" stroke="#5c6c48" stroke-width="1.5" stroke-dasharray="5 4"/><text x="${zx+5}" y="${t+12}">Re = 0</text>`;}
 for(const s of raw){const pts=spec.scatter&&!s.line?s.points.filter((_,i)=>i%Math.max(1,Math.floor(s.points.length/1500))===0):reduce(s.points);if(spec.scatter&&!s.line)content+=pts.map(p=>{const [x,y]=xy(p);return `<circle cx="${x}" cy="${y}" r="${s.radius||2.7}" fill="${s.color}" opacity=".7"/>`;}).join('');else content+=`<path d="${pts.map((p,i)=>{const[x,y]=xy(p);return `${i?'L':'M'}${x},${y}`;}).join(' ')}" fill="none" stroke="${s.color}" stroke-width="1.8" ${s.dashed?'stroke-dasharray="5 4"':''}/>`;}
 content+=`<text class="axis-label" x="${l+pw/2}" y="${height-6}" text-anchor="middle">${esc(spec.xLabel)}</text><text class="axis-label" transform="translate(15 ${t+ph/2}) rotate(-90)" text-anchor="middle">${esc(spec.yLabel)}</text><circle data-cursor r="5" fill="none" stroke="#3d482e" visibility="hidden"/>`;svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.innerHTML=content;spec.rendered=raw;};
 const inspect=(sx,sy)=>{if(!xy)return;let best,bestD=Infinity;for(const s of spec.rendered)for(const p of s.points){const[x,y]=xy(p);const d=spec.scatter?(x-sx)**2+(y-sy)**2:Math.abs(x-sx);if(d<bestD){bestD=d;best={s,p,x,y};}}if(!best)return;const {s,p,x,y}=best;svg.querySelector('[data-cursor]').setAttribute('cx',x);svg.querySelector('[data-cursor]').setAttribute('cy',y);svg.querySelector('[data-cursor]').setAttribute('visibility','visible');tip.textContent=`${s.label} · ${spec.xLabel}: ${fmt(p.x,4)} · ${spec.yLabel}: ${fmt(p.y,4)}${p.note?` · ${p.note}`:''}`;};
 const inspectPointer=e=>{const rect=svg.getBoundingClientRect();inspect((e.clientX-rect.left)*width/rect.width,(e.clientY-rect.top)*height/rect.height);};svg.addEventListener('pointermove',inspectPointer);svg.addEventListener('pointerdown',inspectPointer);svg.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const pts=spec.rendered[0]?.points||[];index=e.key==='Home'?0:e.key==='End'?pts.length-1:Math.max(0,Math.min(pts.length-1,index+(e.key==='ArrowRight'?1:-1)));if(pts[index])inspect(...xy(pts[index]));});draw();const observer=new ResizeObserver(draw);observer.observe(el);observers.push(observer);});}
