import {fmt} from './charts.js';
const point=p=>Array.isArray(p)?p:[p?.x||0,p?.y||0];
function belt(a,b,R,r,color){const dx=b[0]-a[0],dy=b[1]-a[1],d=Math.hypot(dx,dy);if(d<=Math.abs(R-r)||d===0)return '';const u=[dx/d,dy/d],v=(R-r)/d,k=Math.sqrt(1-v*v),n=[v*u[0]+k*u[1],v*u[1]-k*u[0]],m=[v*u[0]-k*u[1],v*u[1]+k*u[0]],ap=[a[0]+R*n[0],a[1]+R*n[1]],bp=[b[0]+r*n[0],b[1]+r*n[1]],am=[a[0]+R*m[0],a[1]+R*m[1]],bm=[b[0]+r*m[0],b[1]+r*m[1]];return `<path d="M ${ap} L ${bp} A ${r} ${r} 0 0 1 ${bm} L ${am} A ${R} ${R} 0 1 1 ${ap}" fill="none" stroke="${color}" stroke-width="2"/><circle cx="${a[0]}" cy="${a[1]}" r="${R}" fill="#fff" fill-opacity=".75" stroke="${color}" stroke-width="2"/><circle cx="${b[0]}" cy="${b[1]}" r="${r}" fill="#fff" fill-opacity=".75" stroke="${color}" stroke-width="2"/>`;}
export function mechanismMarkup(){return `<svg class="mechanism" tabindex="0" role="img" aria-label="Belt-coupled linkage. Fixed pivot A, knee B, wheel C. Three separate axial belt planes."></svg><div class="belt-key"><span><i style="background:#667e3e"></i>Plane 1 · grounded guide A→B</span><span><i style="background:#286d8a"></i>Plane 2 · drive A→B</span><span><i style="background:#8a5682"></i>Plane 3 · drive B→C</span></div><p class="hint">Pulley radii are schematic; tooth-count ratios define transmission. Concentric pulleys shown in side view; the three belts occupy separate axial planes. The compound drive pulleys at B rotate freely relative to both links.</p><output class="mini-readout" id="pose-readout"></output>`;}
export function drawMechanism(svg,p,c,{forces=true,workspace=[],showWorkspace=false}={}){if(!svg||!p)return;const rawA=point(p.points?.A||p.A),rawB=point(p.points?.B||p.B),rawC=point(p.points?.C||p.C);const L=(c.geometry?.upperLength||.25)+(c.geometry?.lowerLength||.25),wr=c.geometry?.wheelRadius||.08;const w=Math.max(310,svg.clientWidth),h=svg.clientHeight||470,sc=Math.min((h-130)/(L+2*wr),w*.5/(L+2*wr)),ax=w*.5,ay=90;const tr=([x,y])=>[ax+x*sc,ay-y*sc];const A=tr(rawA),B=tr(rawB),C=tr(rawC);const line=(a,b,color,width=9)=>`<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" stroke="${color}" stroke-width="${width}" stroke-linecap="round"/>`;let content=`<defs><marker id="force-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#b46f07"/></marker></defs><path d="M ${ax-45} ${ay-43} h90 v-9 M ${ax-32} ${ay-52} l-8 -10 M ${ax-12} ${ay-52} l-8 -10 M ${ax+8} ${ay-52} l-8 -10 M ${ax+28} ${ay-52} l-8 -10" stroke="#89947c" fill="none"/><line x1="${ax}" x2="${ax}" y1="${ay-40}" y2="${h-30}" stroke="#d4dcc9" stroke-dasharray="5 5"/>`;
 if(showWorkspace&&workspace.length)content+=`<path d="${workspace.map((v,i)=>{const [x,y]=tr(point(v.points?.C||v.C||[v.x,v.y]));return `${i?'L':'M'}${x},${y}`;}).join(' ')}" fill="none" stroke="#9aab81" stroke-width="4" stroke-dasharray="3 5"/>`;
 content+=line(A,B,'#a0ad83',13)+line(B,C,'#d6bf83',13);const g=c.geometry||{},guideRatio=g.guideRatio||2,guideRadius=Math.min(31,sc*L*.13);content+=belt(A,B,guideRadius,guideRadius/guideRatio,'#667e3e');content+=belt(A,B,12,12/(g.driveRatio1||1),'#286d8a');content+=belt(B,C,16,16/(g.driveRatio2||1),'#8a5682');content+=`<circle cx="${C[0]}" cy="${C[1]}" r="${wr*sc}" fill="#fff" fill-opacity=".65" stroke="#45513a" stroke-width="4"/>`;
 const mark=(center,r,angle,color)=>line([center[0]+Math.cos(angle)*r*.55,center[1]-Math.sin(angle)*r*.55],[center[0]+Math.cos(angle)*r,center[1]-Math.sin(angle)*r],color,2.5);content+=mark(A,guideRadius,Math.PI/2,'#667e3e')+mark(B,guideRadius/guideRatio,p.beta,'#667e3e')+mark(A,12,p.phi||0,'#286d8a')+mark(B,12/(g.driveRatio1||1),p.compoundAngle||0,'#286d8a')+mark(B,16,p.compoundAngle||0,'#8a5682')+mark(C,16/(g.driveRatio2||1),p.wheelAngle||0,'#8a5682');
 const angle=p.wheelAngle||0;for(let i=0;i<4;i++){const t=angle+i*Math.PI/2;content+=line(C,[C[0]+Math.cos(t)*wr*sc,C[1]-Math.sin(t)*wr*sc],'#45513a',2);}const t=angle;content+=`<circle cx="${C[0]+Math.cos(t)*wr*sc}" cy="${C[1]-Math.sin(t)*wr*sc}" r="4" fill="#b57709"/>`;
 if(c.spring?.type==='linear'&&p.spring?.anchor&&p.spring?.attachment){const S=tr(point(p.spring.anchor)),T=tr(point(p.spring.attachment));content+=line(S,T,'#b67a08',3);content+=`<circle cx="${S[0]}" cy="${S[1]}" r="4" fill="#b67a08"/>`;}else if(c.spring?.type!=='none'){const r=40;const pts=Array.from({length:100},(_,i)=>{const a=Math.PI*.15+i/99*Math.PI*1.45,rr=r+(i>5&&i<94?Math.sin(i/99*Math.PI*20)*3:0);return[ax+Math.cos(a)*rr,ay+Math.sin(a)*rr];});content+=`<path d="${pts.map((v,i)=>`${i?'L':'M'}${v}`).join(' ')}" fill="none" stroke="#bc8418" stroke-width="2.5"/>`;}
 if(forces){const load=c.load||{},fx=load.forceX||0,fy=load.forceY||0,max=Math.max(1,Math.hypot(fx,fy)),len=Math.min(70,max*.2);if(max>1)content+=`<line x1="${C[0]}" y1="${C[1]}" x2="${C[0]+fx/max*len}" y2="${C[1]-fy/max*len}" stroke="#b46f07" stroke-width="2.5" marker-end="url(#force-arrow)"/><text x="${C[0]+20}" y="${C[1]+wr*sc+21}">External load (${fmt(fx)}, ${fmt(fy)}) N</text>`;}
 for(const [name,a,dx,dy] of [['A',A,-45,-20],['B',B,25,-8],['C',C,-45,6]])content+=`<circle cx="${a[0]}" cy="${a[1]}" r="4" fill="#343f29"/><text x="${a[0]+dx}" y="${a[1]+dy}" font-weight="bold">${name}</text>`;
 content+=`<text x="16" y="23">Fixed chassis · x → / y ↑</text><text x="16" y="44" class="mono">q = ${fmt(p.q*180/Math.PI)}° · β = ${fmt(p.beta*180/Math.PI)}°</text><text x="16" y="${h-13}" class="mono">Wheel center x = ${fmt(rawC[0]*1000)} mm · y = ${fmt(rawC[1]*1000)} mm</text>`;svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.innerHTML=content;}
